  services:
    db:
      image: mysql:8.0
      container_name: mysql-container
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"  # Expose MySQL à l'extérieur
      volumes:
        - ./mysql_data:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-container
      restart: always
      environment:
        PMA_HOST: db           # Nom du service MySQL
        PMA_USER: root
        PMA_PASSWORD: root
      ports:
        - "8080:80"           # Accès phpMyAdmin via http://localhost:8080
      depends_on:
        - db
